# Generated by Django 3.2.15 on 2024-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title'], 'verbose_name': 'заметки', 'verbose_name_plural': 'Заметки'},
        ),
    ]
